config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end

  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  root :to => "players#index"

  devise_for :users
  resources :users, :only => [:index, :show, :update]

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :matches

  def name
    return "Season ##{self.ordinal}"
  end

  def to_s
    name
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < InheritedResources::Base
  actions :create, :destroy, :edit, :index, :new, :show, :update
  before_action :authenticate_user!

  def create
    params.permit!
    super
  end

  def new_match
    @season = Season.find(params[:id])
    @match = @season.matches.build
  end

  def update
    params.permit!
    super
  end

end

app/views/seasons/_form.html.erb
<% if @season.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

    <ul>
    <% @season.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@season, {html: {class: "uk-form"}}) do |f| %>
  <fieldset class="uk-form-horizontal">
    <div class="uk-form-row">
      <label class="uk-form-label" for="ordinal"><%= f.label :ordinal -%>:</label>
      <div id="ordinal" class="uk-form-controls"><%= f.text_field :ordinal %></div>
    </div>
    <div class="uk-form-row">
      <label class="uk-form-label" for="start_year"><%= f.label :start_year -%>:</label>
      <div id="start_year" class="uk-form-controls"><%= f.text_field :start_year %></div>
    </div>
    <div class="uk-form-row">
      <label class="uk-form-label" for="stop_year"><%= f.label :stop_year -%>:</label>
      <div id="stop_year" class="uk-form-controls"><%= f.text_field :stop_year %></div>
    </div>
    <div class="uk-form-row">
      <%= f.submit class: "uk-button uk-button-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/seasons/_index.html.erb
<table class="uk-table uk-align-center">
  <tr>
    <th>Name</th>
    <th>Start Year</th>
    <th>Stop Year</th>
    <th># of Matches</th>
<% if changes_allowed? %>
    <th class="actions">Actions</th>
<% end %>
  </tr>
<% @seasons.each do |season| %>
  <tr>
    <td><%= link_to "#{season}", season %></td>
    <td class="numeric"><%= season.start_year %></td>
    <td class="numeric"><%= season.stop_year %></td>
    <td class="numeric"><%= season.matches.count %></td>
<% if changes_allowed? %>
    <td class="actions">
      <%= link_to "Change", edit_season_path(season) %>&nbsp;/
      <%= link_to "Remove", season, :confirm => "Are you sure?", :method => :delete %>
    </td>
<% end %>
  </tr>
<% end %>
</table>
<p/>
<% if changes_allowed? %>
  <%= link_to "Add a New Season", new_season_path, class: "uk-button" %>
<% end %>

app/views/seasons/_show.html.erb
<div class='uk-panel uk-width-5-10'>
  <table class="uk-table uk-align-center">
    <tr>
      <th>Name:</th>
      <td>Season <%= @season.ordinal %></td>
    </tr>
    <tr>
    <th><%= link_to("Matches:", matches_path, :season_id => @season.id) -%></th>
      <td>
        <% for match in @season.matches %>
          <%= link_to "#{match}", match_path(match) %><br/>
        <% end %>
        <% if @season.matches.empty? %><i>None</i><% end %>
      </td>
    </tr>
  <% if changes_allowed? %>
    <tr>
      <th class="actions">Actions: </th>
      <td class="actions">
        <%= link_to "Add a Match", {:action => 'new_match', :id => @season.id}, class: "uk-button" %>
        <%= link_to "Edit", edit_resource_path(@season), class: "uk-button"  %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/seasons/index.html.erb
<table border="1" cellpadding="5" cellspacing="1">
  <tr>
    <th>Name</th>
    <th>Start Year</th>
    <th>Stop Year</th>
    <th># of Matches</th>
    <th>Actions</th>
  </tr>

<% @seasons.each do |season| %>
  <tr>
    <td><%= link_to "#{season}", season %></td>
    <td align="right"><%= season.start_year %></td>
    <td align="right"><%= season.stop_year %></td>
    <td align="right"><%= season.matches.count %></td>
    <td>
      <%= link_to "Change", edit_season_path(season) %>&nbsp;/
      <%= link_to "Remove", season, :confirm => "Are you sure?", :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "Add a New Season", new_season_path %>

app/views/seasons/new_match.html.erb
<div class="uk-container uk-container-center uk-margin-top uk-width-8-10">
  <h3>New Match for <%= @season.name %></h3>
  <%= render :partial => "matches/form", :locals => {:match => @match} %>
</div>