config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end

  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  root :to => "players#index"

  devise_for :users
  resources :users, :only => [:index, :show, :update]

end

app/models/player.rb
class Player < ActiveRecord::Base

  has_many :results, dependent: :restrict_with_error
  has_many :games, through: :results

  scope :active, ->{where("1 = 1")}

  def <=>(another_player)
    self.total_points <=> another_player.total_points
  end

  def self.sorted_by_first_name
    order('first_name, last_name')
  end

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def non_scoring_results(season_id)
    self.season_results(season_id) - self.scoring_results(season_id)
  end

  def scoring_results(season_id)
    ary = self.season_results(season_id).sort {|x, y| y.points <=> x.points}
    ary[0..5]
  end

  def season_games(season_id)
    Game.joins(:players, :match => :season).where('seasons.id = ? AND players.id = ?', season_id, self.id)
  end

  def season_results(season_id)
    Result.joins(:player, :game => [:match => :season]).where('seasons.id = ? AND players.id = ?', season_id, self.id)
  end

  def season_total_points(season_id)
    sql = %Q(
      WITH scoring_results AS (
        SELECT
          ROUND(CAST(10 * (SQRT(game_results.player_count) / SQRT(results.place)) * (1 + LOG(10 + 0.25)) AS numeric), 2) AS points
        FROM
          results
        INNER JOIN "players" ON "players"."id" = "results"."player_id"
        INNER JOIN "games" ON "games"."id" = "results"."game_id"
        INNER JOIN "matches" ON "matches"."id" = "games"."match_id"
        INNER JOIN "seasons" ON "seasons"."id" = "matches"."season_id"
        INNER JOIN (SELECT game_id, COUNT(player_id) AS player_count FROM results GROUP BY game_id) AS game_results ON game_results.game_id = games.id
        WHERE
          (seasons.id = #{season_id} AND players.id = #{self.id})
        ORDER BY
          points DESC
        LIMIT 6
      )
      SELECT SUM(points) AS total_points FROM scoring_results;
    )

    result = ActiveRecord::Base.connection.execute(sql)
    result.first['total_points'].to_f
  end

  def to_s
    full_name
  end

  def total_points
    self.season_total_points(Season.last.id)
  end

end

app/controllers/players_controller.rb
class PlayersController < InheritedResources::Base

  actions :create, :destroy, :edit, :new, :show, :update
  before_action :authenticate_user!

  def create
    params.permit!
    super
  end

  def index
    @page_title = "All Players"
    self.set_season
    @players = Player.all.sort.reverse
  end

  def move
    if ["move_lower", "move_higher"].include?(params[:method]) and params[:game_player_id] =~ /^\d+$/
      gp = Result.find(params[:game_player_id])
      gp.send(params[:method]) unless gp.nil?
    end
    redirect_to :controller => :games, :action => :show, :id => gp.game.id
  end

  def set_season
    @season = (params[:season_id].nil?) ? Season.last : Season.find(params["season_id"])
  end

  def show
    self.set_season
    show! { @page_title = "Showing a Player" }
  end

  def update
    params.permit!
    super
  end

end

app/views/players/_form.html.erb
<% if @player.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@player.errors.count, "error") %> prohibited this Player from being saved:</h2>

    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@player, {html: {class: "uk-form"}}) do |f| %>
  <table>
    <tr>
      <th>Player #</th>
      <td><%= "#{@player.id}" %></td>
    </tr>
    <tr>
      <th><%= f.label :first_name %></th>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <th><%= f.label :last_name %></th>
      <td><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <th><%= f.label :email %></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th><%= f.label :phone %></th>
      <td><%= f.text_field :phone %></td>
    </tr>
  </table>
  <p/>

  <div>
    <%= f.submit "Update Player", {class: "uk-button"} %>
  </div>

<% end %>

app/views/players/_index.html.erb
<table class="uk-table uk-align-center">
  <tr>
    <th>Place</th>
    <th>Player</th>
    <th>Total Points</th>
    <th>Games Played</th>
    <% if changes_allowed? %>
      <th>Actions</th>
    <% end %>
  </tr>
  <%
    i = 1
    @players.each do |player|
      if player.season_games(@season.id).count > 0
    %>
    <tr>
      <td class="uk-width-1-10"><%= i %></td>
      <td class="uk-width-2-10"><%= link_to("#{player.full_name}", player) %></td>
      <td class="uk-width-1-10"><%= player.season_total_points(@season.id) %></td>
      <td class="uk-width-1-10"><%= player.season_games(@season.id).count %></td>
      <% if changes_allowed? %>
        <td class="uk-width-2-10">
          <%= link_to "Change", edit_player_path(player) %>&nbsp;/
          <%= link_to "Remove", player, :confirm => "Are you sure?", :method => :delete %>
        </td>
      <% end %>
    </tr>
    <%
      i += 1
    end
  end
%>
</table>
<p/>
  <% if changes_allowed? %>
    <%= link_to "Add a New Player", new_player_path, class: "uk-button" %>
  <% end %>

app/views/players/_show.html.erb
<div class='uk-grid'>
  <div class='uk-panel uk-width-1-2'>
    <h3>Details</h3>
    <table class="uk-table uk-align-center">
      <tr>
        <th>Player</th>
        <td><%= @player.full_name %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= @player.email %></td>
      </tr>
      <tr>
        <th>Phone</th>
        <td><%= @player.phone %></td>
      </tr>
    </table>
  </div>

  <div class='uk-panel uk-width-1-2'>
    <h3>Games Played</h3>
    <% if @player.season_games(@season.id).empty? %>
      <i>None</i>
    <% else %>

    <h4>Scoring</h4>
    <table class="uk-table uk-align-center">
      <tr>
        <th>Match</th>
        <th>Game</th>
        <th>Place</th>
        <th>Points</th>
      </tr>
    <% for result in @player.scoring_results(@season.id) %>
      <tr>
        <td><%= link_to "#{result.game.match}", match_path(result.game.match) %></td>
        <td class="numeric"><%= link_to "#{result.game.ordinal}", game_path(result.game) %></td>
        <td class="numeric"><%= result.place %></td>
        <td class="numeric"><%= result.points %></td>
      </tr>
    <%   end %>
    </table>

    <h4>Non-Scoring</h4>
    <table class="uk-table uk-align-center">
      <tr>
        <th>Match</th>
        <th>Game</th>
        <th>Place</th>
        <th>Points</th>
      </tr>
    <%   for result in @player.non_scoring_results(@season.id) %>
      <tr>
        <td><%= link_to "#{result.game.match}", match_path(result.game.match) %></td>
        <td class="numeric"><%= link_to "#{result.game.ordinal}", game_path(result.game) %></td>
        <td class="numeric"><%= result.place %></td>
        <td class="numeric"><%= result.points %></td>
      </tr>
    <%   end %>
    </table>
    <% end %>
  </div>
</div>