config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end

  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  root :to => "players#index"

  devise_for :users
  resources :users, :only => [:index, :show, :update]

end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :season
  has_many :games

  def to_s
    "#{self.match_date}"
  end

end

app/controllers/matches_controller.rb
class MatchesController < InheritedResources::Base

  actions :create, :destroy, :edit, :new, :show, :update
  before_action :authenticate_user!

  def create
    params.permit!
    super do |format|
      format.html {redirect_to :controller => :seasons, :action => :show, :id => Season.last}
    end
  end

  def index
    @season = (params[:season_id].nil?) ? Season.last : Season.find(params["season_id"])
    @matches = @season.matches
  end

  def new_game
    @match = Match.find(params[:id])
    @game = @match.games.build
    @players = Player.all.sort {|a, b| a.full_name <=> b.full_name}
  end

  def update
    params.permit!
    super
  end

end

app/views/matches/_form.html.erb
<% if @match.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@match.errors.count, "error") %> prohibited this Match from being saved:</h2>

    <ul>
    <% @match.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@match, {html: {class: "uk-form"}}) do |f| %>
  <fieldset class="uk-form-horizontal">
    <div class="uk-form-row">
      <label class="uk-form-label" for="match_date"><%= f.label :match_date %></label>
      <div id="match_date" class="uk-form-controls"><%= f.text_field :match_date %></div>
    </div>
    <div class="uk-form-row">
      <label class="uk-form-label" for="season"><%= f.label :season %></label>
      <div id="season" class="uk-form-controls"><%= f.collection_select(:season_id, Season.all, :id, :name)%></div>
    </div>
    <div class="uk-form-row">
      <%= f.submit class: "uk-button uk-button-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/matches/_index.html.erb
<table class="uk-table uk-align-center">
  <tr>
    <th class="uk-width-2-10">Season</th>
    <th class="uk-width-2-10">Match</th>
<% if changes_allowed? %>
    <th class="uk-width-2-10">Actions</th>
  </tr>
<% end %>
<%
  if !@matches.empty?
%>
  <tr>
  <td rowspan="<%= @matches.count %>"><%= link_to @season, season_path(@season.id) -%></td>
<%
      @matches.each { |match|
%>
    <td><%= link_to "#{match}", match %></td>
<% if changes_allowed? %>
    <td class="actions">
      <%= link_to "Change", edit_match_path(match), class: "uk-button uk-button-primary uk-button-small" -%>
      <%= link_to "Remove", match, class: "uk-button uk-button-danger uk-button-small", method: :delete, data: {confirm: "Are you sure?"} %>
    </td>
<% end %>
  </tr>
<%
      }
    else
%>
  <tr>
    <td><%= @season %></td>
    <td colspan="4">No Matches</td>
  </tr>
<%
  end
%>
</table>
<p/>
<% if changes_allowed? %>
  <%= link_to "Add a New Match", new_match_path, class: "uk-button" %>
<% end %>

app/views/matches/_show.html.erb
<div class='uk-grid'>
  <div class='uk-panel uk-align-center uk-width-1-2'>
    <table class="uk-table uk-align-center">
      <tr>
        <th class="uk-text-right">Match Id:</th>
        <td><%= @match.id -%></td>
      </tr>
      <tr>
        <th class="uk-text-right">Date:</th>
        <td><%= @match.match_date %></td>
      </tr>
      <tr>
        <th class="uk-text-right">Season:</th>
        <td><%= link_to @match.season.name, season_path(@match.season) %></td>
      </tr>
      <tr>
        <th class="uk-text-right">Games:</th>
        <td>
          <% for game in @match.games %>
            <%= link_to "#{game}", game_path(game) %><br/>
          <% end %>
          <% if @match.games.empty? %><i>None</i><% end %>
        </td>
      </tr>
      <% if changes_allowed? %>
        <tr>
          <th class="uk-text-right">Actions</th>
          <td>
            <%= link_to "Add a Game", {:action => 'new_game', :id => @match.id}, class: "uk-button" -%>
            <%= link_to "Edit", edit_resource_path(@season), class: "uk-button"  %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/matches/index.html.erb
<table border="1" cellpadding="5" cellspacing="1">
  <tr>
    <th>Season</th>
    <th>Match</th>
    <th colspan="2">Actions</th>
  </tr>
<%
  Season.all.each do |season|
    if !season.matches.empty?
%>
  <tr>
  <td rowspan="<%= season.matches.count %>"><%= season %></td>
<%
      season.matches.each { |match| 
%>
    <td><%= link_to "#{match}", match %></td>
    <td>
      <%= link_to "Change", edit_match_path(match) %>&nbsp;/
      <%= link_to "Remove", match, :confirm => "Are you sure?", :method => :delete %>
    </td>
  </tr>
<%
      }
    else
%>
  <tr>
    <td><%= season %></td>
    <td colspan="4">No Matches</td>
  </tr>
<%
    end 
  end
%>
</table>
<br />
<%= link_to "Add a New Match", new_match_path %>

app/views/matches/new_game.html.erb
<h3>New Game for <%= @match %></h3>
<%= render :partial => "games/form", :locals => {:game => @game} %>