config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end

  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  root :to => "players#index"

  devise_for :users
  resources :users, :only => [:index, :show, :update]

end

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="uk-navbar">
  <a class="uk-navbar-brand" href="/"><i class="uk-icon-home uk-icon-small"></i></a>

  <% if user_signed_in? %>
    <ul class="uk-navbar-nav uk-hidden-small">
      <li><%= link_to 'Players', players_path %></li>
      <li><%= link_to 'Games', games_path %></li>
      <li><%= link_to 'Matches', matches_path %></li>
      <li><%= link_to 'Seasons', seasons_path %></li>
    </ul>
    <ul class="uk-navbar-nav uk-hidden-small uk-navbar-flip">
      <% if current_user.try(:admin?) %>
        <!-- li><%= link_to 'Admin', '/admin' %></li -->
        <li><%= link_to 'Users', users_path %></li>
      <% end %>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  <% else %>
    <ul class="uk-navbar-nav uk-hidden-small uk-navbar-flip">
      <li class="uk-active">
        <%= link_to "Sign In", new_user_session_path %>
      </li>
    </ul>
  <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="uk-height-1-1">
  <head>
    <title><%= ApplicationHelper.ShortName %> &raquo; <%= @page_title %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/js/uikit.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body class="uk-height-1-1">
    <div class="uk-container uk-container-center uk-margin-top uk-width-6-10" role="main">
      <%= link_to(image_tag("sppl_banner.gif", :alt => "#{ApplicationHelper.Name}", class: "uk-align-center"), "/" ) %>

      <% if alert %>
        <div class="uk-alert uk-alert-danger" role="alert"><%= alert %></div>
      <% end %>

      <% if notice %>
        <div class="uk-alert uk-alert-success" role="alert"><%= notice %></div>
      <% end %>

      <%= render "layouts/navigation" %>

      <%= yield %>

      <div class='uk-vertical-align uk-text-center uk-height-1-1'>
        <div class='panel panel-info'>
          <div class="uk-vertical-align-middle">
            <p>Version 5 :: Copyright 2011-19 :: <a href="http://www.ngzax.com">Daryl Richter</a> :: All Rights Reserved.</p>
          </div>
        </div>
      </div>
    </div> <!-- /container -->

  </body>
</html>